######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 22 12:37:42 2012
######################################################################

TEMPLATE = app
QT += network
QT += sql
TARGET = server.bin
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lboost_serialization

# Input
HEADERS += server.h database.h message.h user.h
SOURCES += main.cpp server.cpp database.cpp message.cpp user.cpp

