######################################################################
# Automatically generated by qmake (2.01a) lun. oct. 15 10:33:51 2012
######################################################################

TEMPLATE = app
TARGET = client.bin 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += authWindow.h
SOURCES += authWindow.cpp main.cpp
